### ISSUE TITLE
ClariusNewProcessedImageFn not called on Windows

### ISSUE THREAD

**Issue by mischkew** [clariusdev/listener#1]
Dear Clarius-Team, dear @clariusk,

First of all, we've been using your API packages for a while and they provide a great backbone for our software, thanks for your efforts!

**Observed Behaviour**

When compiling the example CLI application on Windows, the `ClariusNewProcessedImageFn` is not called and no images are streamed since API v7.1.0. The same behaviour worked in v6.1.5. 

The line of interest is this: https://github.com/clariusdev/listener/blob/master/src/example/console/main.cpp#L85

* We use the listener.dll on Windows 10.
* The probe's IP and Clarius Cast port are set correctly when launching the example.
* The Clarius cast option is enabled in the app and set to "Research".
* The Clarius app and probe have been updated to v7.1.0. 
* The behaviour happens if the host device is both, either iOS or Android.
* The Windows laptop is in the same WiFi as the probe by using a Windows hotspot. 
* The Windows laptop would not connect to the Direct WiFi of the probe.
* Disabling the firewall does not help.
* The freeze/ unfreeze, depth and gain operations work.
* When running the example CLI application on Linux Ubuntu 18.10, it works with API v7.1.0

**Expected Behaviour**

The Windows API should receive processed images from the probe, when the CLI software prints "imaging".

**Steps to Reproduce**

* Compile the console example application on Windows 10
* Run the CLI with your probes IP, port and keydir
* Observe how no images are received, when the probe is unfrozen

I hope the behaviour description is sufficient. We're happy to provide any more details for you, i.e. if you need certain stacktraces etc. Thanks for the great work and support!

Best,
Sven

**Comment by clariusk** [comment]
Please try disabling Windows Defender Firewall, or adding an exception for the API program you built.

**Comment by mischkew** [comment]
Thanks Kris!

We did the following now:
* build the project from scratch from the provided visual studio project
* disabled all firewalls
* disabled all of windows defender
* tried to use the research port as well as a dynamically assigned port
* connected via a Windows WiFi hotspot as well as the direct WiFi

All of these solutions allow for freezing/ unfreezing.
None of these solutions sends the image stream.

Do you propose anything else? Can we send you any debug logs from the probe?

Cheers!

**Comment by mischkew** [comment]
After further conversation offline with @clariusk, we found out that this bug only appears in the console example application, not in the QT application.

**Comment by smistad** [comment]
I have the same issue after the 7.1 update on windows, worked fine before. Firewall disabled etc.
Do you have any more details on the cause of this issue?

**Comment by clariusk** [comment]
might have to do with some internal Qt bindings, we'll be investigating

**Comment by Alyosha-Karamazov** [comment]
We may have determined the root cause and are hopefully close to a fix.

**Comment by clariusk** [comment]
the windows binaries have been updated and should resolve the issue reported

**Comment by smistad** [comment]
I can confirm the fix is working. Thanks

**Comment by mischkew** [comment]
I can confirm as well. Firewall exceptions are required. Thanks!
