### ISSUE TITLE
Import error for pylisten in python example

### ISSUE THREAD

**Issue by NodOzz** [clariusdev/listener#2]
Dear Clarius-Team, 

thanks for your efforts in building this API. We recently purchased one of your ultrasound scanners and are very happy with the imaging quality. Now we are starting to work with the API. After being able to use the API from the C++ examples, we now also wanted to try the python examples. 

However, we have problems importing the _pylisten_ module for your example code (_pylistener.py_ and _pysidelistener.py_).

I tried to add the _pylisten.pyd_ and the _listen.dll_ to the PYTHONPATH or also copied it in the same directory as the python files, but I keep on getting an import error: 
`ImportError: DLL load failed while importing pylisten: The specified module could not be found` 

I use Python3.8 on Win10 64Bit. 

( Please excuse this trivial question, I just wanted to rule this one out: The `import pylisten` refers to the import of the _pylisten.pyd_ DLL from the binaries download, and has nothing to do with the pip-package with the same name (https://github.com/MycroftAI/pylisten), correct? )

Do you have any hint on what I might be doing wrong? Any help is much appreciated. 

Best, 
Daniel

**Comment by clariusk** [comment]
Hi Daniel

Thanks for using Clarius and trying out our samples. I have not tried using python under Windows, however under Linux, I follow these steps to get the python examples running:
- Install Pillow (latest PIL library) and PySide2 using pip
- Copy pylisten.so and liblisten.so to {listener_path}/src/python
- Execute: LD_LIBRARY_PATH=. python3 {clarius_python_example}.py

For your specific error, without explicitly testing under Windows, ensure listen.dll is in the same/proper path as pylisten.pyd

Thanks
Kris

**Comment by NodOzz** [comment]
Hi Kris, 

thank you very much for your great help. Under Linux it works now like a charm! 

Under Windows I still encounter the same problem, even after adding the respective path to Windows' %PATH%. 
But I am happy as long as I can run it under Linux.

Thanks and best reagards,
Daniel
