### ISSUE TITLE
 error: undefined reference to `clariusDisconnect'

### ISSUE THREAD

**Issue by wangzhicheng-1997** [clariusdev/listener#4]
Hello, I have downloaded the lib and added it to the specified path. There is still the problem of not being able to find the function definition. How should I solve it? Thank you.
![Error reminder](https://user-images.githubusercontent.com/57751665/92197797-5ddcfe00-eea5-11ea-8e91-e1a6cd5de5d1.png)

**Comment by clariusk** [comment]
Clarius does not provide compiler/programming support, but you must ensure that the program links to the listen.lib library that Clarius provides in the binaries. You can read the Qt Creator manual to learn more about using that IDE and compilation options: https://doc.qt.io/qtcreator/index.html
