### ISSUE TITLE
Which port to provide the listener?

### ISSUE THREAD

**Issue by olim0** [clariusdev/listener#5]
Hi,
We have recently acquire a phased-array Clarius probe and are very excited to develop upon it!

However, we are facing issue understanding which port to provide when launching the listener.
Based on the pylistener.py, we found in main():
```
parser.add_argument(‘--port’, ‘-p’, dest=‘port’, type=int, help=‘port of the probe’, required=True)
```
based on listen.h, we have:
```
/// @param[in] port the tcp port that the scanner’s listener is setup on
```
From our understanding, 3 devices are running :
probe, mobile/tablet running clarius app, the device running the listener
Is this port related to the probe or to the device running the listener?

We tried to connect all devices to the probe wifi or on a common LAN wifi using the preset port “5828” we saw in the code and using the IP provided in Clarius app.
For exemple, running on the probe wifi with the console exemple:
```
$ build/console -a 192.168.1.1 -p 5828
starting listener...
error: connect failure: Exception ocurred (Error connecting to TCP socket: Connection refused)
could not connect to scanner
```
NB: we can ping the probe from the device running the listener when running this.

we have also scanned the open ports of the probe and only found the ports 36481 and 36929 open. we tried to used them unsuccessfully.

My guess is that we are misunderstanding the connection process? Could you please enlighten us?

Thx!

NB:
This was tried on mac and ubuntu
The software version is 7.1.0-104 and we are using the latest release of the listener

**Comment by clariusk** [comment]
Hi there, once you have purchased the Listen API software license for your probe, the App will display (after connecting to the probe) the corresponding IP and port that the API will work on.

**Comment by lydiazoghbi** [comment]
Hi! I am having the same issue, using a wireless Clarius C3, Ubuntu 18, software version 7.1.0 for listener API. I have the Listen API software license for the probe (though I don't recollect activating anything, just connected to the mobile app). All devices are on the probe's wifi, TCP connection established with the probe, but every time I get a message "could not connect to scanner". I was wondering what resolved the issue for @olim0. Thanks!
